name: 'Integration Tests'

on:
  push:
    branches:
      - master
      - v2
  pull_request:
    branches:
      - master
      - v2

jobs:
  baseline:
    name: OpenLDAP Integration Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm

      - name: Install Packages
        run: npm ci
      - name: Start OpenLDAP
        run: docker compose up -d --wait
      - name: Run Tests
        run: npm run test:integration
      - name: Stop OpenLDAP
        if: always()
        run: docker compose down
